package com.example.laara.ui.theme

import androidx.compose.ui.graphics.Color


//bright theme
val Primary40 = Color(0xFF68124c)
val Secondary40 = Color(0xFF7d5168)
val Tertiary40 = Color(0xFF6d1810)
val Error40 = Color(0xFFba1a1a)
//Containers
val PrimaryContainer40 = Color(0xFF933871)
val SecondaryContainer40 = Color(0xFFffcce4)
val TertiaryContainer40 = Color(0xFF9c3b2e)
val ErrorContainer40 = Color(0xFFffdad6)

// on primary
val OnPrimary40 = Color(0xFFffffff)
val OnSecondary40 = Color(0xFFffffff)
val OnTertiary40 = Color(0xFFffffff)
val OnError40 = Color(0xFFffffff)

//on containers
val OnPrimaryContainer40 = Color(0xFFffffff)//#ffffff
val OnSecondaryContainer40 = Color(0xFF5e364c)//#5e364c
val OnTertiaryContainer40 = Color(0xFFffffff)//#ffffff
val OnErrorContainer40 = Color(0xFF410002)//#410002

val SurfaceDim = Color(0xffe6d6db)


/* Dark theme */

val Primary80 = Color(0xFFffaed9)
val Secondary80 = Color(0xFFeeb7d2)
val Tertiary80 = Color(0xFFffb4a8)
val Error80 = Color(0xFFffb4ab)
//Containers
val PrimaryContainer80 = Color(0xFF761f58)
val SecondaryContainer80 = Color(0xFF5b3349)
val TertiaryContainer80 = Color(0xFF7c2319)
val ErrorContainer80 = Color(0xFF93000a)

// on primary
val OnPrimary80 = Color(0xFF5e0844)
val OnSecondary80 = Color(0xFF492439)
val OnTertiary80 = Color(0xFF621009)
val OnError80 = Color(0xFF690005)

//on containers
val OnPrimaryContainer80 = Color(0xFFffcbe4)//#ffffff
val OnSecondaryContainer80 = Color(0xfffdc5e0)//#5e364c
val OnTertiaryContainer80 = Color(0xFFffcec7)//#ffffff
val OnErrorContainer80 = Color(0xFFffdad6)//#410002

//on s
val SurfaceDim80 = Color(0xFF191115)
val inverseSurface80 = Color(0xffeedee4)
val outline = Color(0xffa08b94)




val primaryLight = Color(0xFF68124C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF933871)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF7D5168)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFCCE4)
val onSecondaryContainerLight = Color(0xFF5E364C)
val tertiaryLight = Color(0xFF6D1810)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF9C3B2E)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F8)
val onBackgroundLight = Color(0xFF21191D)
val surfaceLight = Color(0xFFFFF8F8)
val onSurfaceLight = Color(0xFF21191D)
val surfaceVariantLight = Color(0xFFF4DCE6)
val onSurfaceVariantLight = Color(0xFF53424A)
val outlineLight = Color(0xFF85727A)
val outlineVariantLight = Color(0xFFD7C1CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372E32)
val inverseOnSurfaceLight = Color(0xFFFDEDF2)
val inversePrimaryLight = Color(0xFFFFAED9)
val surfaceDimLight = Color(0xFFE6D6DB)
val surfaceBrightLight = Color(0xFFFFF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F4)
val surfaceContainerLight = Color(0xFFFAEAEF)
val surfaceContainerHighLight = Color(0xFFF4E4E9)
val surfaceContainerHighestLight = Color(0xFFEEDEE4)

val primaryLightMediumContrast = Color(0xFF68124C)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF933871)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF5E364C)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF95677F)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF6D1810)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF9C3B2E)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F8)
val onBackgroundLightMediumContrast = Color(0xFF21191D)
val surfaceLightMediumContrast = Color(0xFFFFF8F8)
val onSurfaceLightMediumContrast = Color(0xFF21191D)
val surfaceVariantLightMediumContrast = Color(0xFFF4DCE6)
val onSurfaceVariantLightMediumContrast = Color(0xFF4E3E46)
val outlineLightMediumContrast = Color(0xFF6C5A62)
val outlineVariantLightMediumContrast = Color(0xFF89767E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF372E32)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFDEDF2)
val inversePrimaryLightMediumContrast = Color(0xFFFFAED9)
val surfaceDimLightMediumContrast = Color(0xFFE6D6DB)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F8)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF0F4)
val surfaceContainerLightMediumContrast = Color(0xFFFAEAEF)
val surfaceContainerHighLightMediumContrast = Color(0xFFF4E4E9)
val surfaceContainerHighestLightMediumContrast = Color(0xFFEEDEE4)

val primaryLightHighContrast = Color(0xFF480033)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF762058)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF39162B)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF5E364C)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF4D0101)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF7C2319)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F8)
val onBackgroundLightHighContrast = Color(0xFF21191D)
val surfaceLightHighContrast = Color(0xFFFFF8F8)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF4DCE6)
val onSurfaceVariantLightHighContrast = Color(0xFF2E2027)
val outlineLightHighContrast = Color(0xFF4E3E46)
val outlineVariantLightHighContrast = Color(0xFF4E3E46)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF372E32)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFE5F0)
val surfaceDimLightHighContrast = Color(0xFFE6D6DB)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F8)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFFF0F4)
val surfaceContainerLightHighContrast = Color(0xFFFAEAEF)
val surfaceContainerHighLightHighContrast = Color(0xFFF4E4E9)
val surfaceContainerHighestLightHighContrast = Color(0xFFEEDEE4)

val primaryDark = Color(0xFFFFAED9)
val onPrimaryDark = Color(0xFF5E0844)
val primaryContainerDark = Color(0xFF761F58)
val onPrimaryContainerDark = Color(0xFFFFCBE4)
val secondaryDark = Color(0xFFEEB7D2)
val onSecondaryDark = Color(0xFF492439)
val secondaryContainerDark = Color(0xFF5B3349)
val onSecondaryContainerDark = Color(0xFFFDC5E0)
val tertiaryDark = Color(0xFFFFB4A8)
val onTertiaryDark = Color(0xFF621009)
val tertiaryContainerDark = Color(0xFF7C2319)
val onTertiaryContainerDark = Color(0xFFFFCEC7)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191115)
val onBackgroundDark = Color(0xFFEEDEE4)
val surfaceDark = Color(0xFF191115)
val onSurfaceDark = Color(0xFFEEDEE4)
val surfaceVariantDark = Color(0xFF53424A)
val onSurfaceVariantDark = Color(0xFFD7C1CA)
val outlineDark = Color(0xFFA08B94)
val outlineVariantDark = Color(0xFF53424A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEEDEE4)
val inverseOnSurfaceDark = Color(0xFF372E32)
val inversePrimaryDark = Color(0xFF983C75)
val surfaceDimDark = Color(0xFF191115)
val surfaceBrightDark = Color(0xFF40373B)
val surfaceContainerLowestDark = Color(0xFF130C10)
val surfaceContainerLowDark = Color(0xFF21191D)
val surfaceContainerDark = Color(0xFF261D21)
val surfaceContainerHighDark = Color(0xFF30282C)
val surfaceContainerHighestDark = Color(0xFF3C3236)

val primaryDarkMediumContrast = Color(0xFFFFB5DB)
val onPrimaryDarkMediumContrast = Color(0xFF330023)
val primaryContainerDarkMediumContrast = Color(0xFFD46EA9)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFF3BBD6)
val onSecondaryDarkMediumContrast = Color(0xFF2B0A1E)
val secondaryContainerDarkMediumContrast = Color(0xFFB4829C)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFBAAF)
val onTertiaryDarkMediumContrast = Color(0xFF370000)
val tertiaryContainerDarkMediumContrast = Color(0xFFE16E5E)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF191115)
val onBackgroundDarkMediumContrast = Color(0xFFEEDEE4)
val surfaceDarkMediumContrast = Color(0xFF191115)
val onSurfaceDarkMediumContrast = Color(0xFFFFF9F9)
val surfaceVariantDarkMediumContrast = Color(0xFF53424A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDCC5CE)
val outlineDarkMediumContrast = Color(0xFFB29DA6)
val outlineVariantDarkMediumContrast = Color(0xFF927E86)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEEDEE4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF31282C)
val inversePrimaryDarkMediumContrast = Color(0xFF7D255D)
val surfaceDimDarkMediumContrast = Color(0xFF191115)
val surfaceBrightDarkMediumContrast = Color(0xFF40373B)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF130C10)
val surfaceContainerLowDarkMediumContrast = Color(0xFF21191D)
val surfaceContainerDarkMediumContrast = Color(0xFF261D21)
val surfaceContainerHighDarkMediumContrast = Color(0xFF30282C)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3236)

val primaryDarkHighContrast = Color(0xFFFFF9F9)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFB5DB)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFF9F9)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFF3BBD6)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFFF9F8)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFBAAF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF191115)
val onBackgroundDarkHighContrast = Color(0xFFEEDEE4)
val surfaceDarkHighContrast = Color(0xFF191115)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF53424A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9F9)
val outlineDarkHighContrast = Color(0xFFDCC5CE)
val outlineVariantDarkHighContrast = Color(0xFFDCC5CE)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEEDEE4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF56003D)
val surfaceDimDarkHighContrast = Color(0xFF191115)
val surfaceBrightDarkHighContrast = Color(0xFF40373B)
val surfaceContainerLowestDarkHighContrast = Color(0xFF130C10)
val surfaceContainerLowDarkHighContrast = Color(0xFF21191D)
val surfaceContainerDarkHighContrast = Color(0xFF261D21)
val surfaceContainerHighDarkHighContrast = Color(0xFF30282C)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3C3236)







